DROP TABLE IF EXISTS PUBLICATION_AUTHOR;
DROP TABLE IF EXISTS QUOTE;
DROP TABLE IF EXISTS PUBLICATION;
DROP TABLE IF EXISTS AUTHOR;

DROP SEQUENCE IF EXISTS author_seq;
DROP SEQUENCE IF EXISTS quote_seq;
DROP SEQUENCE IF EXISTS publication_seq;

CREATE SEQUENCE author_seq START WITH 4;
CREATE SEQUENCE quote_seq START WITH 343;
CREATE SEQUENCE publication_seq START WITH 33;

CREATE TABLE AUTHOR (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE PUBLICATION (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255),
    publishing_year VARCHAR(255),
    wiki_url VARCHAR(255),
    is_short_story BOOLEAN DEFAULT FALSE
);

CREATE TABLE QUOTE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    quote TEXT NOT NULL
);

CREATE TABLE PUBLICATION_AUTHOR (
    publication_id INT NOT NULL,
    author_id INT NOT NULL,
    PRIMARY KEY (publication_id, author_id),
    FOREIGN KEY (publication_id) REFERENCES PUBLICATION(id),
    FOREIGN KEY (author_id) REFERENCES AUTHOR(id)
);